### ISSUE TITLE
How can I export the map from the program custommap with another suffix like (SQLite db) because I need it in this format

### ISSUE THREAD

**Issue by mohammed-android** [markoteittinen/custom-maps#12]

**Comment by markoteittinen** [comment]
Custom Maps only supports kmz and kml formats. You can find the map files you've created in CustomMaps folder in the internal storage of the phone.

The kmz files are simply zip files containing the map image file and the coordinate description in xml format (file name extension .kml). If you rename the .kmz file to .zip file, then most unpacking programs can give you access to the files inside. You can then convert the data yourself to whatever format you need.

**Comment by mohammed-android** [comment]
Thank you
This program is wonderful and unique.
But I need your help with this because I am a university student surveyor
Can you modify the program to export the file (SQLite db)
Forgive me if you took a little bit of your time
I am really interested in this program

‫في الخميس، 12 ديسمبر 2019 في 7:45 ص تمت كتابة ما يلي بواسطة ‪Marko
Teittinen‬‏ <‪notifications@github.com‬‏>:‬

**Comment by markoteittinen** [comment]
There is no standard SQLite DB format for map data like Custom Maps. Each database has different data tables and columns, so such feature would be useful only for the single person for whom it was created. So it is best if the person who needs to have the data in a database transfers it there. They are the only one who knows the format the data needs to be written to, and they are the only one who benefits from that work.
