### ISSUE TITLE
No check mark in menu for location details

### ISSUE THREAD

**Issue by mganss** [markoteittinen/custom-maps#15]
If you enable "Location details" from the menu there is no check mark shown in the menu indicating that this feature is enabled.

This may not be easy because it says at https://developer.android.com/guide/topics/ui/menus.html#checkable

> Note: Menu items in the Icon Menu (from the options menu) cannot display a checkbox or radio button. If you choose to make items in the Icon Menu checkable, you must manually indicate the checked state by swapping the icon and/or text each time the state changes.

**Comment by markoteittinen** [comment]
Thank you for pointing this issue out. This has been fixed in my latest dev system, and I will include the fix in the next beta release (1.6 beta 5)
