### ISSUE TITLE
Show map location in external app

### ISSUE THREAD

**Issue by mganss** [markoteittinen/custom-maps#16]
It would be nice to have the ability to open the map's (center) location in an external app, e.g. Google Maps. The use case for me is "scouting",  i.e. compare the Custom Maps map with an external app's map before I'm actually at the location.

This could be a menu item or a button in the location details section, possibly next to the lat/long values.

Here are the docs: https://developer.android.com/guide/components/intents-common.html#Maps

**Comment by markoteittinen** [comment]
There's already two ways of doing this.

1) You can touch-and-hold the map in the map selection list until a menu pops up, and then select "Modify map", and then immediately select "preview" which will show the map overlaid with Google Maps. You can get back to map selection list by hitting "back" twice, or re-saving the map.

2) Install Google Earth on your device, and use a file manager to open Custom Maps folder, and select the kmz-file for the map you want to view. Your device should ask if you want to open the map in Custom Maps or in Google Earth. If you select Google Earth, you will see the map overlaid over Google Earth, and you can view it in 3D.

But there have been requests to be able to see the maps overlaid with Google Maps even without entering the "modify map" mode. I have considered doing that, but I haven't implemented such mode yet.

Does either one of the first two help you, or would you like the third, unimplemented option? Or did I misunderstand your request.

**Comment by mganss** [comment]
I think you may have misunderstood. I believe my request is actually much simpler. Once I have fully calibrated a map and I'm using it I would like to just have the option of opening an external map app (e.g. Google Maps) with the coordinates of the current center position of the map. No need for an overlay, just another menu item.

**Comment by markoteittinen** [comment]
No, I understood you. Yours is just the first request for such simple feature that I think it might not get much use and thus would mostly be just "cluttering" the UI. But if you only need to see the map (and not do searches or use other Google Maps features), then providing a quick button/menu option while viewing the map image to see it overlaid on Google Maps might be a win for many users. It should not be even too difficult to implement, as the map alignment preview already does the same thing. Obviously this would be possible only when the device has a data connection.

**Comment by mganss** [comment]
🆗 fair enough. IMHO this feature would be more useful than the "Share map" feature that's already available from the menu. But the overlay option would be nice, too. Regarding the data connection: Won't the embedded Google map use an offline map if you have downloaded one for the area you're looking at? Of course, this wouldn't be an issue if you could use an external app (OsmAnd, say). Just sayin' 😉
