### ISSUE TITLE
how can i use cutom maps in my app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markoteittinen/custom-maps#2]
```
i want to get source of custom-maps android app
1. when i try for http://custom-maps.googlecode.com/svn/trunk/ 
custom-maps-read-only i gor error 404 exception



```

Original issue reported on code.google.com by `ashwith...@gmail.com` on 11 Mar 2013 at 12:03

**Comment by markoteittinen** [comment]
Custom Maps source code is now hosted at GitHub.com:
https://github.com/markoteittinen/custom-maps/
