### ISSUE TITLE
Too large map

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markoteittinen/custom-maps#3]
```
It tells me it can't load a map because it is too large. 
What is biggest map it can load? 

Regards, m
```

Original issue reported on code.google.com by `myn...@gmail.com` on 22 Mar 2013 at 11:28

**Comment by markoteittinen** [comment]
The largest map Custom Maps can open is limited only by the memory in your Android device and the amount of memory Android OS allows an individual app to use. This varies between devices and OS versions. The app provides an estimated maximum recommended image size (in megapixels, 1 megapixel = 1024x1024) on Preferences screen. That number tries to be safe, so in most cases you can actually use somewhat larger map image, and on some modern devices a much larger image.
