### ISSUE TITLE
Enhancement request: ability to change background color

### ISSUE THREAD

**Issue by GoogleCodeExporter** [markoteittinen/custom-maps#4]
```
If the map is a transparent PNG with black lines, it is impossible to set 
reference points, because the app background is also black, so lines are 
invisible. It would be nice to be able to set the background in app settings.

Thank you for the great app!
```

Original issue reported on code.google.com by `mikekaga...@gmail.com` on 28 Aug 2013 at 11:14

**Comment by markoteittinen** [comment]
My recommendation is to open the PNG file with transparent background in a graphics editor like GIMP and to add a non-transparent background color for the map image. The resulting image can then be used conveniently in Custom Maps.
